name: light_toast
description: "A lightweight Flutter package for displaying customizable toast messageswith support for icons, images, and configurable durations."
version: 0.0.6
homepage: https://github.com/Anees7757/light_toast.git

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter: